// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nehjowujifqiialxoxwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5laGpvd3VqaWZxaWlhbHhveHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTY0NDIsImV4cCI6MjA2MzkzMjQ0Mn0.9IChsEqhurD8fhL2DVbFEKALhNo_Iu-MJlVjjMEWm8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);